### ISSUE TITLE
can you link some Literature's you are following for the project.

### ISSUE THREAD

**Issue by mkingupta** [idnavid/spkr_diarization#1]
It seems that you are not going with the I-Vector approach so can you please link some literature which might help me understand the code better.

**Comment by idnavid** [comment]
The current project is still in its initial phase. Also, the final product will be tailored towards a specific application, so not sure if it'll be useful for you. 
If you're interested in an implementation of an ivector system, I'm working to make our private diarization project publicly available. It'll be a couple of months before that is finalized. 
As for literature, AudioSeg has a good documentation (includes theory and references).

**Comment by mkingupta** [comment]
thanks that would be really helpful.
also can you tell what tools you have employed for the i-vector extraction and the clustering part in your project.

**Comment by idnavid** [comment]
We've added C++ libraries to Kaldi. So i-vectors (and other implementations) use Kaldi's i-vector extraction. 
We have a few clustering options: 
Hierarchical + BIC 
Integer Linear Programming + variations.

**Comment by mkingupta** [comment]
that sounds really great . actually i am also trying kaldi's i-vector extraction and plda scoring for speaker clustering.It would be really helpful if i can have some insights on your implementation. Kindly update me if it's plausible.
